Map<String, String> enUS = {
  "signin": "Sign In",
  "welcomekbcquizapp": "Welcome \n To KBC Quiz App",
  "continuingtnc": "By Continuing, You Are Agree With Our TnC",
  "dailyquiz": "DAILY QUIZ",
  "leaderboard": "Leaderboard",
  "howtouse": "How To Use",
  "aboutus": "About Us",
  "logout": "Logout",
  "kbcquizgame": "KBC - Quiz Game",
  "urlcaraslider":
      "https://images.pexels.com/photos/792381/pexels-photo-792381.jpeg?auto=compress&cs=tinysrgb&w=600",
  "richestintheworld": "Richest Player In The World",
  "profile": "Profile",
  "rank": "Rank",
  "startquiz": "START QUIZ",
  "quizapp": "KBC Quiz App",
  "donothaveenoughmoney": "You do not have enough money to buy this QUIZ!",
  "ok": "OK",
  "prizes": "PRIZES",
  "asktheexpert": "Ask The\n Expert",
  "fifty50": "Fifty\n 50",
  "jokerquestion": "Joker\n Question",
  "audiencepoll": "Audience\n Poll",
  "lifeline": "LifeLine",
  "quitgame": "QUIT GAME",
  "wantquitgame": "DO YOU WANT TO QUIT THE GAME",
  "getrsinacc": "You will get Rs. In Your Account.",
  "quit": "Quit",
  "cancel": "Cancel",
  "retry": "Retry",
  "Ohsorry": "Oh Sorry!",
  "ansincorrect": "YOUR ANSWER IS INCORRECT",
  "gotorewards": "Go To Rewards",
  "youwon": "You Won",
  "quitquiz": "DO YOU WANT TO EXIT QUIZ ?",
  "sharewithfriends": "Share With Friends",
  "cong": "CONGRATULATIONS!",
  "correctans": "YOUR ANSWER IS CORRECT",
  "nextquestion": "Next Question",
  "okay": "Okay!",
  "no": "No!"
};
